version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: omnitrack_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omnitrack
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: omnitrack_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
