name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # If you want to test multiple node versions
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd web
          npm install
      - name: Build web
        run: |
          cd web
          npm run build
      - name: Test web
        run: |
          cd web
          npm test
